//
//  ProductDetailModels.swift
//  AZCleanSwift
//
//  Created by Sefa Aycicek on 6.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ProductDetail
{
  // MARK: Use cases
  
    enum GetDetailData
      {
        struct Request
        {
        }
        struct Response
        {
            let productResponse : Products?
            let hasFav : Bool?
            let hasBas : Bool?
        }
        struct ViewModel
        {
            let title: String
            let desc: String
            let priceMain: String
            let priceOld: String
            let hasFav: Bool
            let hasBas: Bool
            let images: [String]
            let productId: String
            let discount: String
        }
      }
    
    enum AddBasket
    {
      struct Request
      {
          let productId: String
          let itemCount: Int
      }
      struct Response
      {
          let isFavAdded:Bool
      }
      struct ViewModel
      {
          let requestMessage:String
      }
    }
    enum AddFavorite
    {
      struct Request
      {
          let productId: String
      }
      struct Response
      {
          let hasFav: Bool
      }
      struct ViewModel
      {
          let hasFav: UIImage
          let requestMessage:String

      }
    }
}
