//
//  ProductDetailViewController.swift
//  AZCleanSwift
//
//  Created by Sefa Aycicek on 6.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Kingfisher

protocol ProductDetailDisplayLogic: AnyObject
{
  func display(viewModel: ProductDetail.GetDetailData.ViewModel)
  func displayFav(viewModel: ProductDetail.AddFavorite.ViewModel)
  func displayBas(viewModel: ProductDetail.AddBasket.ViewModel)
}

class ProductDetailViewController: UIViewController, ProductDetailDisplayLogic
{

    
    
    
  var interactor: (ProductDetailBusinessLogic & ProductDetailDataStore)?
  var router: (ProductDetailRoutingLogic & ProductDetailDataPassing)?

    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var descLabel: UILabel!
    
    @IBOutlet weak var priceOld: UILabel!
    @IBOutlet weak var priceNew: UILabel!
    
    @IBOutlet weak var imageView: UIImageView!
    
    @IBOutlet weak var imageHeightConstraint: NSLayoutConstraint!
    
    @IBOutlet weak var disView: UIView!
    @IBOutlet weak var disLabel: UILabel!
    
    override func viewDidLoad()
  {
    super.viewDidLoad()
      getInitData()
    
  }
  
    
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func getInitData()
  {
    let request = ProductDetail.GetDetailData.Request()
    interactor?.handle(request: request)
  }
  
  func display(viewModel: ProductDetail.GetDetailData.ViewModel)
  {
      
      let image = UIImage(named: viewModel.hasFav ? "isFavorite1" : "isFavorite0")
      self.navigationItem.rightBarButtonItem = UIBarButtonItem.init(image: image, style: .plain, target: self, action: #selector(favClicked))
      
      titleLabel.text=viewModel.title
      descLabel.text=viewModel.desc
      priceNew.text="\(viewModel.priceMain) TL"
      priceOld.attributedText="\(viewModel.priceOld) TL".strikeThrough()
      
      disView.layer.cornerRadius=24
      disLabel.text="%\(viewModel.discount)"
      
      self.imageView.kf.setImage(with: URL(string: viewModel.images.first ?? "")) { image in
          print("resim yüklendik sonra")
          //image.get().image.size
          
          //width : 3 height 2 = 3/2 = 1.5
          
          // w ?  : h : 35
          
          //w 30: h:?
          if let size = try? image.get().image.size {
              let ratio = size.width / size.height
              //self.imageWidthConstraint.constant = self.imageHeightConstraint.constant * ratio
              //self.imageHeightConstraint.constant = self.imageHeightConstraint.constant * ratio
              //self.imageHeightConstraint.constant = size.width / ratio
          }
      }
  }
    
    @objc private func favClicked(){
        let request=ProductDetail.AddFavorite.Request(productId: String(interactor?.product?.id ?? 0))
        interactor?.handle(request: request)
    }
    
    func displayFav(viewModel: ProductDetail.AddFavorite.ViewModel) {
        self.navigationItem.rightBarButtonItem = UIBarButtonItem.init(image: viewModel.hasFav, style: .plain, target: self, action: #selector(favClicked))
        
    }
    
    func displayBas(viewModel: ProductDetail.AddBasket.ViewModel) {
        
    }
    

}
